### ISSUE TITLE
EVM token issue

### ISSUE THREAD

**Issue by xtoben22** [universal9622/evm-token-tracking#2]
#1  why do you need to implement like this about evm token tracking feature?

**Comment by coin96** [comment]
so as you know, it's first mint this evm token and it is related to the goal of this project
let me see and we need to define our thinking again

**Comment by xtoben22** [comment]
ok
let me see
maybe we have a meeting to discuss again

**Comment by coin96** [comment]
yup
ok

**Comment by xtoben22** [comment]
i ll contact you again
